const path1 = 'https://files.d20.io/images/';
const path2 = 'https://s3.amazonaws.com/files.d20.io/images/';
const path3 = 'https://files.d20.io/marketplace/';

var templates={
    'sandbag': {
        'name': 'sandbag',
        'type': 'construct',
        'img': '395757768/-NNZb8mH90MnERzaknPQfg/max.png?1717592146',
        'hp': 99999,
        'ac': 10,
        'str': 1,
        'dex': 1,
        'con': 10,
        'int': 10,
        'wis': 10,
        'cha': 10,
        'attack_stat': 'str',
        'proficiency_bonus': 3,
        'proficient_saves': ['con'],
        'resistances': [],
        'immunities': [],
        'vulnerabilities': [],
    }, 
    'lilguy': {
        'name': 'lilguy',
        'type': 'humanoid',        
        'img': '387448924/BWiMuNmuqZUiqgmTiVI8PQ/max.png?1712273921',
        'hp': 10,
        'ac': 10,
        'str': 10,
        'dex': 12,
        'con': 10,
        'int': 10,
        'wis': 10,
        'cha': 10,
        'attack_stat': 'dex',
        'proficiency_bonus': 3,
        'proficient_saves': [],
        'resistances': [],
        'immunities': [],
        'vulnerabilities': [],
    },   
    'shark': {
        'name': 'Shark',
        'type': 'beast',        
        'img': '407950871/V3Dt6tGXOErFP2Z5WsBwuw/max.png?1725367369',
        'hp': 20,
        'ac': 12,
        'str': 18,
        'dex': 13,
        'con': 15,
        'int': 1,
        'wis': 10,
        'cha': 4,
        'attack_stat': 'str',
        'proficiency_bonus': 2,
        'proficient_saves': [], 
        'resistances': [],
        'immunities': [],
        'vulnerabilities': [],
    },
    'terrorbird1': {
        'name': 'Terrorbird',
        'type': 'aberration',        
        'img': '402212233/jk9_UyNfGrafckQuERjJMg/max.jpg?1721841642',
        'hp': 45,
        'ac': 16,
        'str': 13,
        'dex': 11,
        'con': 14,
        'int': 9,
        'wis': 15,
        'cha': 9,
        'attack_stat': 'wis',
        'proficiency_bonus': 3,
        'proficient_saves': [],  
        'resistances': [],
        'immunities': [],
        'vulnerabilities': [],      
    },
    'terrorbird2': {
        'name': 'Terrorbird',
        'type': 'aberration',        
        'img': '402212238/vvgOozmkzkPlyG0K8N4BgA/max.jpg?1721841644',
        'hp': 50,
        'ac': 17,
        'str': 12,
        'dex': 17,
        'con': 11,
        'int': 13,
        'wis': 12,
        'cha': 11,
        'attack_stat': 'dex',
        'proficiency_bonus': 3,
        'proficient_saves': [],
        'resistances': [],
        'immunities': [],
        'vulnerabilities': [],        
    },
    'terrorbird3': {
        'name': 'Terrorbird',
        'type': 'aberration',        
        'img': '402212231/40pff0HtVBuZUDQHKgz_tQ/max.png?1721841640',
        'hp': 37,
        'ac': 12,
        'str': 7,
        'dex': 14,
        'con': 11,
        'int': 16,
        'wis': 12,
        'cha': 5,
        'attack_stat': 'int',
        'proficiency_bonus': 3,
        'proficient_saves': [],
        'resistances': [],
        'immunities': [],
        'vulnerabilities': [],        
    },    
    'assassin': {
        'name': 'Assassin',
        'type': 'humanoid',        
        'img': '411766250/Nkg7VsrIdJafQX7tZD9rUw/max.png?1727801795',
        'hp': 78,
        'ac': 15,
        'str': 11,
        'dex': 16,
        'con': 14,
        'int': 13,
        'wis': 11,
        'cha': 10,
        'attack_stat': 'dex',
        'proficiency_bonus': 3,
        'proficient_saves': ['dex', 'int'],
        'resistances': [],
        'immunities': [],  
        'vulnerabilities': [],            
    },
    'mangler': {
        'name': 'Angel?',
        'type': 'aberration',        
        'img': '384077540/5Z04F9QAnahL2MlgbLFUKQ/max.png?1710167731',
        'hp': 27,
        'ac': 14,
        'str': 9,
        'dex': 18,
        'con': 17,
        'int': 6,
        'wis': 15,
        'cha': 7,
        'gmnotes': 'https://www.dndbeyond.com/monsters/4941857-shadow-mangler',
        'rechargeDie': '1d6',
        'rechargeNumber': 5,
        'rechargeAbilityReady': true,        
        'attack_stat': 'dex',
        'proficiency_bonus': 3,
        'proficient_saves': [],
        'resistances': [],
        'immunities': ['poison','poisoned','necrotic','charmed','prone','frightened','deafened','blinded'],
        'truesight': true,
        'vulnerabilities': [],          
    },
    'strangler': {
        'name': 'Strangler',
        'type': 'aberration',        
        'img': '384077535/XqvEu3AORdie5RVsPrsMkw/max.png?1710167726',
        'hp': 67,
        'ac': 16,
        'str': 21,
        'dex': 18,
        'con': 19,
        'int': 5,
        'wis': 7,
        'cha': 7,
        'attack_stat': 'str',
        'proficiency_bonus': 3,
        'proficient_saves': [],
        'resistances': [],
        'immunities': [],
        'vulnerabilities': [],          
    },
    'alkilith': {
        'name': 'Alkilith',
        'type': 'fiend',        
        'img': '403848266/sJTQbILTJFb6jEmD7PCw_w/max.png?1722814862',
        'hp': 157,
        'ac': 17,
        'str': 12,
        'dex': 19,
        'con': 22,
        'int': 6,
        'wis': 11,
        'cha': 7,
        'attack_stat': 'dex',
        'proficiency_bonus': 4,
        'damage_type': 'acid',        
        'proficient_saves': ['dex','con'],
        'resistances': ['acid', 'cold', 'fire', 'lightning','nmbludgeoning', 'nmslashing', 'nmpiercing'],
        'immunities': ['poison', 'charmed', 'frightened', 'poisoned'],
        'vulnerabilities': [],
        //startOfTurnTrait is an effect imposed on others at the start of their turn. startOfTurn is what this does on the start of its own turn
        'startOfTurnTrait': function(me,token) {
            let circle = {
                x: me.token.get('left'),
                y: me.token.get('top'),
                r: (me.token.get('width')/2) + 420
            };
            let target = getTargetArea(token);
            if (liesWithinCircle(circle,token)) {
                if (!hasMarker(token,'confusion')) echo(token.get('name') + ' must roll a wisdom save to resist the maddening effects of the Alkilith\'s presence');
            }
        },
        'magicResistance': true,
    }, 'avatarOfTorment': {
        'name': 'Avatar of Torment',
        'type': 'aberration',        
        'img': '415831725/Xfti_L1S3Yl__tq_mrbnAw/max.png?1730487029',
        'hp': 312,
        'ac': 15,
        'str': 26,
        'dex': 23,
        'con': 24,
        'int': 18,
        'wis': 23,
        'cha': 15,
        'attack_stat': 'str',
        'proficiency_bonus': 6,
        'proficient_saves': ['wis','cha'],
        'resistances': ['nmbludgeoning', 'nmslashing', 'nmpiercing'],
        'immunities': ['incapacitated', 'charmed', 'frightened', 'paralyzed'],
        'vulnerabilities': [],
        'startOfTurn': async function() {
            let roll = await rollDice(this.token.get('name'), "2d10");
            roll = roll['total'];
            let prevHP = this.token.get('bar3_value')
            if (prevHP != null && !isNaN(prevHP)) {
                let newHP = Math.min(this.hp, Number(prevHP) + roll);
                this.token.set('bar3_value', newHP);
                if (newHP > Number(prevHP)) echo(this.name + ' regained ' + (newHP - Number(prevHP)) + ' hit points');
            }
        },
        'endOfTurn': function() {
            echo('Avatar of Torment has regained its legendary actions');
        }
    }, 'zombie': {
        'name': 'Zombie',
        'type': 'undead',        
        'img': '418511203/wGwGsQGIwOH8UrGd9oVUlg/max.png?1732295791',
        'hp': 22,
        'ac': 8,
        'str': 13,
        'dex': 6,
        'con': 16,
        'int': 3,
        'wis': 6,
        'cha': 5,
        'attack_stat': 'str',
        'proficiency_bonus': 2,
        'proficient_saves': ['wis'],
        'resistances': [],
        'immunities': ['poison', 'poisoned'],
        'vulnerabilities': [],
        'damage_die': '1d6',
        'damage_type': 'bludgeoning',
        'group_size': 6,
        'proficient_saves': ['wis'],        
        'gmnotes': 'https://roll20.net/compendium/dnd5e/Zombie#content', 
        'immunities': ['poison','poisoned'],   
        'darkvision': true,
        'turnFunction': async function(me) {
            let target = me.approachPlayer();
            if (target != null) {
                me.basicAttack(target);
            }            
            else me.approachPlayer();
            return target;
        }, 
        'onLethalDamage': async function(me, dmgParams) {
            let dmg = dmgParams['dmg'];
            let isCrit = dmgParams['isCrit'];
            let isRadiant = (dmgParams['dmgType'] == 'radiant');
            if (!isCrit && !isRadiant) {
                let conSave = await rollSave('con', false, false, (5 + Number(dmg)));
                if (conSave) {
                    emphasis(me.get('name') + ' endures the hit with 1 HP');
                    clearMarker(me.token, 'dead');
                    me.token.set({
                        bar3_value: 1
                    });
                    return false;
                }
            } else if (isCrit) {
                emphasis('the critical hit prevents ' + me.get('name') + ' from clinging to its unnatural existence');
            } else if (isRadiant) {
                emphasis('the radiant damage separates the animating force from ' + me.get('name'));
            }
            return true;
        }        
    }, 'intellect devourer': {
        'name': "Intellect Devourer",
        'type': 'aberration',        
        'img': "420945289/kEucUy6UlRRggLfX6ls2Rg/max.png?1734109556",
        'hp': 21,
        'ac': 12,
        'str': 6,
        'dex': 14,
        'con': 13,
        'int': 12,
        'wis': 11,
        'cha': 10,
        'attack_stat': 'dex',
        'attack_bonus': 0,
        'damage_bonus': 0,
        'damage_die': '2d4',
        'add_mod_to_dmg': true,
        'attack_sound': 'slashing',
        'attack_fx': 'pooling-blood',
        'proficiency_bonus': 2,
        'proficient_saves': [],
        'resistances': ['nmbludgeoning', 'nmslashing', 'nmpiercing'],
        'immunities': [],
        'vulnerabilities': [],           
    }, 'Blighted Cactus Dryad': {
        'name': 'Blighted Cactus Dryad',
        'type': 'fey',        
        'img': '431348607/oQCW27VB0VBA1EXaj_sJ6Q/max.png',
        'hp': 58,
        'ac': 16,
        'str': 8,
        'dex': 12,
        'con': 13,
        'int': 7,
        'wis': 18,
        'cha': 18,
        'attack_stat': 'str',
        'proficiency_bonus': 3,
        'proficient_saves': [],
        'resistances': [],
        'immunities': ['poison', 'radiant', 'necrotic', 'poisoned'],
        'vulnerabilities': [],
        'magicResistance': true,
    }, 'Ankheg': {
        'name': 'Ankheg',
        'type': 'beast',        
        'img': '431348599/MlUle4I5ufQCOVK9Ov8LkA/max.png?1741015136',
        'hp': 39,
        'ac': 14,
        'str': 17,
        'dex': 11,
        'con': 13,
        'int': 1,
        'wis': 13,
        'cha': 6,
        'attack_stat': 'str',
        'damage_die': '2d6',
        'damage_type': 'slashing',
        'secondary_damage_die': '1d6',
        'secondary_damage_type': 'acid',
        'proficiency_bonus': 2,
        'proficient_saves': [],
        'resistances': [],
        'immunities': [],
        'vulnerabilities': [],
        'group_size': 3,        
        'turnFunction': async function(me) {
            let target = me.approachPlayer();
            if (target != null) me.basicAttack(target, null, null, null, null, null, function(target, hit) {
                if (hit && !hasMarker(target, 'grappled')) {
                    let w = target.get('width'); let h = target.get('height');
                    if (w <= 140 && h <= 140 && !hasMarker(target,'unconscious') && !hasMarker(target,'incapacitated') && !hasMarker(target,'dead')) {
                        addTokenStatusMarker(target,'grappled', me.token.get('name'));
                        if (hasMarker(target,'grappled')) { //if some effect didn't override the grapple...
                            emphasis(target.get('name') + ' is grappled; they may use an action on their turn to make Athletics or Acrobatics check to escape (DC13)');
                        }
                    }
                }
            });
            else me.approachPlayer();
            return target;
        },        
        'tremorsense': true, //TODO someday you'll want to make this into actual numerical logic
        'receivesAdvFunction': function(me, token) {
            return hasMarker(token, 'grappled', me.token.get('name'));
        }        
    }, 'Young Ankheg': {
        'name': 'Young Ankheg',
        'type': 'beast',        
        'img': '431348599/MlUle4I5ufQCOVK9Ov8LkA/max.png?1741015136',
        'hp': 11,
        'ac': 12,
        'str': 13,
        'dex': 11,
        'con': 13,
        'int': 1,
        'wis': 13,
        'cha': 6,
        'damage_die': '1d6',
        'damage_type': 'slashing',
        'attack_stat': 'str',
        'proficiency_bonus': 2,
        'proficient_saves': [],
        'resistances': [],
        'immunities': [],
        'vulnerabilities': [],
        'group_size': 6,
        'turnFunction': async function(me) {
            let target = me.approachPlayer();
            if (target != null) me.basicAttack(target, null, null, null, null, null, function(target, hit) {
                if (hit && !hasMarker(target, 'grappled')) {
                    let w = target.get('width'); let h = target.get('height');
                    if (w <= 35 && h <= 35 && !hasMarker(target,'unconscious') && !hasMarker(target,'incapacitated') && !hasMarker(target,'dead')) {
                        emphasis(target.get('name') + ' is grappled; they may use an action on their turn to make Athletics or Acrobatics check to escape (DC11)');
                        addTokenStatusMarker(target,'grappled', me.token.get('name'));
                    }
                }
            });            
            else me.approachPlayer();
            return target;
        },
        'tremorsense': true, //TODO someday you'll want to make this into actual numerical logic
        'receivesAdvFunction': function(me, token) {
            debugging("Checking for special advantage condition for " + me.token.get('name'));
            return hasMarker(token, 'grappled', me.token.get('name'));
        }
    }, 'Giant Scorpion': {
        'name': 'Giant Scorpion',
        'type': 'beast',        
        'img': '431348598/6naH8mqZaG2fVu4PFTWBlQ/max.png?1741015136',
        'hp': 52,
        'ac': 15,
        'str': 15,
        'dex': 13,
        'con': 15,
        'int': 1,
        'wis': 9,
        'cha': 3,
        'speed': 40,
        'attack_stat': 'str',
        'proficiency_bonus': 2,
        'damage_die': '1d8',
        'damage_type': 'bludgeoning',
        'proficient_saves': [],
        'resistances': [],
        'immunities': [],
        'vulnerabilities': [],
        'group_size': 1,        
        'blindsight': true,
        'turnFunction': async function(me) {
            let target = me.approachPlayer();
            if (target != null) {
                me.basicAttack(target, null, null, null, null, null, function(target, hit) {
                    if (hit && !hasMarker(target, 'grappled') && !hasMarker(target,'unconscious') && !hasMarker(target,'incapacitated') && !hasMarker(target,'dead')) {
                        emphasis(target.get('name') + ' is grappled; they may use an action on their turn to make Athletics or Acrobatics check to escape (DC12)');
                        addTokenStatusMarker(target,'grappled', me.token.get('name'));
                    }
                });
                me.basicAttack(target, null, null, null, null, null, function(target, hit) {
                    if (hit && !hasMarker(target, 'grappled') && !hasMarker(target,'unconscious') && !hasMarker(target,'incapacitated') && !hasMarker(target,'dead')) {
                        emphasis(target.get('name') + ' is grappled; they may use an action on their turn to make Athletics or Acrobatics check to escape (DC12)');
                        addTokenStatusMarker(target,'grappled', me.token.get('name'));
                    }
                });                
                me.basicAttack(target, null, '1d10+2', 'piercing', null, null, async function(target, hit) {
                    if(hit) {
                        let dmg = await rollDice(me.token.get('name'), '4d10');
                        dmg = dmg['total'];
                        emphasis(target.get('name') + 'must make a DC 12 Constitution saving throw or take ' + dmg + ' poison damage (half on success)');
                    }
                });                  
            }            
            else me.approachPlayer();
            return target;
        },        
    }, 'Umber Hulk': {
        'name': 'Umber Hulk',
        'type': 'monstrosity',        
        'img': '431400197/jqJ4Gmw2DpDFxSldeTKZhA/max.png?1741044294',
        'hp': 93,
        'ac': 18,
        'str': 20,
        'dex': 13,
        'con': 16,
        'int': 9,
        'wis': 10,
        'cha': 10,
        'speed': 30,
        'attack_stat': 'str',
        'proficiency_bonus': 3,
        'damage_die': '2d6',
        'damage_type': 'slashing',
        'proficient_saves': [],
        'resistances': [],
        'immunities': [],
        'vulnerabilities': [],
        'group_size': 1,        
        'tremorsense': true,      
        'darkvision': true,
        'rechargeDie': '1d6',
        'rechargeNumber': 5,
        'rechargeAbilityReady': true,
        'reach': 10,
        'disableAutoTurn': true,
        'turnFunction': async function(me) {
            let evaluateGazeUse = async function() {
                let params = [];
                params['excludeIf'] = function(token) {
                    return hasMarker(token,'confusion');
                }                
                let gazeNowCone = calculateBestCone(me.token, 30, params);
                let nextMove = me.calculateNextMove();
                let nextMoveCone = null;
                if (nextMove.x != null && nextMove.y != null) {
                    params['testX'] = nextMove.x; params['testY'] = nextMove.y;
                    nextMoveCone = calculateBestCone(me.token, 30, params);
                }
                if (gazeNowCone != null) {
                    let params = {'cone': gazeNowCone.cone};
                    if (nextMoveCone == null || nextMoveCone.playersHit.length < gazeNowCone.playersHit.length) {
                        await me.stats.evaluateRechargeAbility(me, params);
                    }
                    else if (nextMoveCone.playersHit.length == gazeNowCone.playersHit.length && nextMoveCone.playersHit[0] <= gazeNowCone.playersHit[0]) {
                        await me.stats.evaluateRechargeAbility(me, params);
                    }
                }                
            }
            if (!me.stats.rechargeAbilityReady) await me.rollToRecharge();
            if (me.stats.rechargeAbilityReady) await evaluateGazeUse();
            let target = me.approachPlayer();
            if (me.stats.rechargeAbilityReady) await evaluateGazeUse();
            if (target != null) {
                let callbackFn = async function(target, hit, roll, hpData) {
                    if (target == null || hit != true || hpData == null) return;
                    let currentHP = hpData['currentHP'] ;
                    let currentTempHP = hpData['currentTempHP'] || 0;
                    let previousHP = hpData['previousHP'] || 0;
                    let previousTempHP = hpData['previousTempHP'] || 0;    
                    let dmg = (previousTempHP - currentTempHP) + (previousHP - currentHP);
                    if (!isNaN(dmg) && dmg > 0) {
                        let healing = Math.floor(dmg/2);
                        let myHP = Number(me.token.get('bar3_value'));
                        let myMaxHP = Number(me.token.get('bar3_max'));
                        let newHP = Math.min((myHP + healing),myMaxHP);
                        await me.token.set({'bar3_value': newHP});
                        emphasis(me.token.get('name') + ' seems a bit healthier after that attack...');
                    }
                }
                me.basicAttack(target, null, null, null, null, null, callbackFn);
                me.basicAttack(target, null, null, null, null, null, callbackFn);
                me.basicAttack(target, null, null, null, null, null, callbackFn);
            }
            else {
                me.approachPlayer();
                if (me.stats.rechargeAbilityReady) await me.stats.evaluateRechargeAbility(me);
            }
        },
        'evaluateRechargeAbility': async function(me, params) {
            if (params == null || params.cone == null) return;
            let abilityParams = {
                'caster': me.token,
                'stat': 'wis',
                'dc': 14,
                'theta': params.cone.angle
            }
            let gazeCallback = function(t, gazeParams) {
                if (!gazeParams.saved) {
                    let token = getToken(t);
                    addTokenStatusMarker(gazeParams.target,'confusion');
                }
            }    
            playSound('hypnoticpattern');
            await coneAoe(abilityParams, 30, 'magic', gazeCallback);
            me.stats.rechargeAbilityReady = false;
        }
    }, 'ghost': {
        'name': 'Ghost',
        'type': 'undead',        
        'img': '451833026/x-Hb3sOChzKKmPDXyXvSGg/thumb.png',
        'hp': 45,
        'ac': 11,
        'str': 7,
        'dex': 13,
        'con': 10,
        'int': 10,
        'wis': 12,
        'cha': 17,
        'speed': 40,
        'attack_stat': 'cha',
        'proficiency_bonus': 2,
        'damage_die': '4d6',
        'damage_type': 'necrotic',
        'proficient_saves': [],
        'resistances': ['acid','fire','lightning','thunder','nmbludgeoning','nmslashing','nmpiercing'],
        'immunities': ['cold','necrotic','poison','charmed','exhaustion','frightened','grappled','paralyzed','petrified','poisoned','prone','restrained'],
        'vulnerabilities': [],
        'group_size': 3,        
        'darkvision': true,
        'rechargeDie': '1d6',
        'rechargeNumber': 6,
        'gmnotes': 'https://roll20.net/compendium/dnd5e/Skeleton#content',
        'rechargeAbilityReady': true,
        'disableAutoTurn': true,        
        'turnFunction': async function(me) {
            let turnAction = 1;
            if (!me.stats.rechargeAbilityReady) {
                turnAction = await rollDice(me.token.get('name'), '1d10') 
                turnAction = turnAction['total'];
                await me.rollToRecharge();
            } else {
                turnAction = await rollDice(me.token.get('name'), '1d10')
                turnAction = turnAction['total'];                
            }
            trace(me.token.get('name') + ' rolled a ' + turnAction + ' when deciding what to do');
            let target = me.approachPlayer();
            //1-6 = attack; 7-8 = possess if possible, else attack; 9-10 = horrifying visage
            if (turnAction <= 8) {            
                if (target != null) {
                    params = {'target': target.get('name')};
                    if (me.stats.rechargeAbilityReady && turnAction >= 7) await me.stats.evaluateRechargeAbility(me,params); 
                    else me.basicAttack(target);
                }
                else {
                    me.approachPlayer();
                }
            } else {
                me.stats.horrifyingVisage(me);
            }
        },
        'evaluateRechargeAbility': async function(me, params) {
            if (params == null || params.target == null) return;
            let token = getToken(params.target);
            if (token == null) return;
            if (token.get('bar3_value'))
            emphasis(token.get('name') + ' must succeed on a DC 13 Charisma save or become possessed by ' + me.token.get('name') + '! (Ignore if this ghost possessed you previously)');
            me.stats.rechargeAbilityReady = false;
        },
        'horrifyingVisage': async function(me, params) {
            for (let i = 0; i < playerTokens.length; i++) {
                if (liesWithinCircle({'x': me.token.get('left'), 'y': me.token.get('top'), r: ((60*70/5)+(me.token.get('width')/2))}, playerTokens[i]) && !hasMarker(playerTokens[i],'frightened')) {
                    emphasis(playerTokens[i].get('name') + ' must succeed on a DC 13 Wisdom save or be frightened by ' + me.token.get('name') + '! (Ignore if this ghost has used its visage on you previously)')
                }
            }            
        }
    }, 'losmalvadosgoon': {
        'name': 'Los Malvados Goon',
        'type': 'humanoid',        
        'img': '435556103/wqcnauvhpKyWdvlALF_FAg/max.png?1743719792',
        'hp': 18,
        'ac': 14,
        'str': 11,
        'dex': 15,
        'con': 10,
        'int': 8,
        'wis': 10,
        'cha': 11,
        'speed': 30,
        'attack_stat': 'dex',
        'proficiency_bonus': 2,
        'damage_die': '2d10',
        'damage_type': 'piercing',
        'proficient_saves': ['dex'],
        'resistances': [],
        'immunities': [],
        'vulnerabilities': [],
        'group_size': 6,        
        'darkvision': false,
    }, 'losmalvadoslieutenant': {
        'name': 'Los Malvados Lieutenant',
        'type': 'humanoid',        
        'img': '436570264/SjnzPWNXWtaYmW7NIiGszw/max.png?1744378133',
        'hp': 43,
        'ac': 15,
        'str': 11,
        'dex': 16,
        'con': 12,
        'int': 13,
        'wis': 14,
        'cha': 14,
        'speed': 30,
        'attack_stat': 'dex',
        'proficiency_bonus': 3,
        'damage_die': '2d10',
        'damage_type': 'piercing',
        'proficient_saves': ['dex'],
        'resistances': [],
        'immunities': [],
        'vulnerabilities': [],
        'group_size': 1,        
        'darkvision': false,
    }, 'jackiemendoza': {
        'name': 'Jackie Mendoza',
        'type': 'humanoid',
        'img': '435667266/ttL4AzHVfL2ZjFGVPKXGzA/thumb.png',
        'hp': 240,
        'ac': 18,
        'str': 13,
        'dex': 23,
        'con': 19,
        'int': 11,
        'wis': 18,
        'cha': 17,
        'speed': 30,   
        'proficiency_bonus': 6,
        'damage_die': '2d12+2',
        'damage_type': 'piercing',
        'proficient_saves': ['str','dex', 'wis', 'cha'],
        'resistances': ['fire','piercing','radiant'],
        'immunities': ['charmed','frightened'],
        'vulnerabilities': [],
        'group_size': 1,       
        'startOfTurn': async function() {
            let roll = await rollDice(this.token.get('name'), "1d6");
            roll = roll['total'];
            let prevHP = this.token.get('bar3_value')
            if (prevHP != null && !isNaN(prevHP)) {
                let newHP = Math.min(this.hp, Number(prevHP) + roll);
                this.token.set('bar3_value', newHP);
                if (newHP > Number(prevHP)) echo(this.name + ' regained ' + (newHP - Number(prevHP)) + ' hit points');
            }
        },        
        'darkvision': false,        
    }, 'Cultist of Loviatar': {
        'name': 'Cultist of Loviatar',
        'type': 'humanoid',
        'img': '440803434/li1IfzTrXcCPd0DwYvjjxQ/original.png',
        'hp': 127,
        'ac': 17,
        'str': 19,
        'dex': 12,
        'con': 18,
        'int': 12,
        'wis': 16,
        'cha': 14,
        'speed': 30,
        'proficiency_bonus': 4,
        'proficient_saves': ['wis','con'],        
        'attack_stat': 'str',
        'damage_die': '1d10+4',
        'damage_type': 'slashing',
        'secondary_damage_die': '2d10',
        'secondary_damage_type': 'necrotic',     
        'group_size': 3,        
        'darkvision': false,
        'rechargeDie': '1d6',
        'rechargeNumber': 5,
        'rechargeAbilityReady': true,        
    } , 'Orson Calloway': {
        'name': 'Orson Calloway',
        'type': 'humanoid',
        'img': '441736703/PjEcesqtFYSJa2iBQtRllg/original.png',
        'hp': 205,
        'ac': 17,
        'str': 13,
        'dex': 20,
        'con': 19,
        'int': 17,
        'wis': 16,
        'cha': 18,
        'speed': 30,
        'proficiency_bonus': 5,
        'proficient_saves': ['str','dex','con', 'cha'],  
        'resistances': ['piercing', 'bludgeoning', 'fire'],
        'immunities': ['charmed','frightened', 'paralyzed', 'restrained'],        
        'initiative_bonus': 5
    } , 'Virgil Thatcher': {
        'name': 'Virgil Thatcher',
        'type': 'humanoid',
        'img': '441841730/HjJ3gulGkDtgCccaJPNydg/original.png',
        'hp': 161,
        'ac': 17,
        'str': 16,
        'dex': 20,
        'con': 20,
        'int': 13,
        'wis': 16,
        'cha': 11,
        'speed': 30,
        'proficiency_bonus': 5,
        'proficient_saves': ['str','dex','con', 'wis'],  
        'resistances': ['piercing', 'bludgeoning', 'fire'],
        'immunities': ['charmed','frightened'],        
        'initiative_bonus': 5
    }, 'Dusty Spurs': {
        'name': 'Dusty Spurs',
        'type': 'humanoid',
        'img': '441974721/1PLpFTuOMRyJKk_rqJIigQ/original.png',
        'hp': 195,
        'ac': 17,
        'str': 23,
        'dex': 14,
        'con': 20,
        'int': 13,
        'wis': 16,
        'cha': 19,
        'speed': 40,
        'proficiency_bonus': 5,
        'proficient_saves': ['str','con'],  
        'resistances': ['piercing', 'bludgeoning', 'slashing'],
        'immunities': ['charmed','frightened','prone','restrained'],        
        'initiative_bonus': 5
    } , 'Red Ice Wizard': {
        'name': 'Red Ice Wizard',
        'type': 'humanoid',
        'img': '433251944/jdKG3VDRTOaCKFE-PeOxKg/max.png?1742224443',
        'hp': 73,
        'ac': 12,
        'str': 20,
        'dex': 20,
        'con': 20,
        'int': 18,
        'wis': 6,
        'cha': 6,
        'speed': 30,
        'proficiency_bonus': 3,
        'proficient_saves': ['int','wis']
    } , 'Rogue': {
        'name': 'Rogue',
        'type': 'humanoid',
        'img': '440839507/361NSEJffr4aPflS9Fpb9g/original.png',
        'hp': 60,
        'ac': 17,
        'str': 8,
        'dex': 20,
        'con': 14,
        'int': 16,
        'wis': 13,
        'cha': 8,
        'speed': 30,
        'proficiency_bonus': 3,
        'proficient_saves': ['dex','int','wis','cha']
    } , 'Cleric': {
        'name': 'Cleric',
        'type': 'humanoid',
        'img': '433251932/1XDR2v-q3JZDCCyf2g6bsQ/thumb.png?1742224441',
        'hp': 66,
        'ac': 17,
        'str': 15,
        'dex': 12,
        'con': 16,
        'int': 8,
        'wis': 18,
        'cha': 8,
        'speed': 30,
        'proficiency_bonus': 3,
        'proficient_saves': ['wis','cha']
    } , 'Cleric': {
        'name': 'Cleric',
        'type': 'humanoid',
        'img': '433251932/1XDR2v-q3JZDCCyf2g6bsQ/max.png?1742224441',
        'hp': 66,
        'ac': 17,
        'str': 15,
        'dex': 12,
        'con': 16,
        'int': 8,
        'wis': 18,
        'cha': 8,
        'speed': 30,
        'proficiency_bonus': 3,
        'proficient_saves': ['wis','cha']
    } , 'Red Ice Fighter': {
        'name': 'Red Ice Fighter',
        'type': 'humanoid',
        'img': '433251934/VJv8u5NUMtpfrYU8UUs9xQ/max.png?1742224441',
        'hp': 99,
        'ac': 21,
        'str': 20,
        'dex': 20,
        'con': 20,
        'int': 8,
        'wis': 6,
        'cha': 6,
        'speed': 30,
        'proficiency_bonus': 3,
        'proficient_saves': ['str','con']
    } , 'Barbarian': {
        'name': 'Barbarian',
        'type': 'humanoid',
        'img': '433251933/2YLw5vzps_c5IccURfbxQQ/max.png?1742224441',
        'hp': 113,
        'ac': 18,
        'str': 18,
        'dex': 16,
        'con': 20,
        'int': 8,
        'wis': 8,
        'cha': 8,
        'speed': 40,
        'proficiency_bonus': 3,
        'proficient_saves': ['str','con']
    }, 'Finch': {
        'name': 'Abercrombie N. Finch',
        'type': 'humanoid',
        'img': '445748811/429wu7BGK9MBr632aAK28g/original.png',
        'hp': 260,
        'ac': 20,
        'str': 19,
        'dex': 16,
        'con': 18,
        'int': 13,
        'wis': 15,
        'cha': 20,
        'speed': 30,
        'proficiency_bonus': 7,
        'proficient_saves': ['str','con','int','wis','cha'],
        'resistances': ['piercing','bludgeoning','slashing','acid','fire','lightning','poison','psychic'],
        'immunities': ['necrotic','charmed','frightened','grappled','prone','paralyzed','restrained'],        
    }, 'Shadowfly': {
        'name': 'Cherub?',
        'type': 'aberration',
        'img': '446141825/C0wH65L4zjBlqw-aCe-A9Q/original.jpg',
        'width': 35,
        'height': 35,
        'hp': 5,
        'ac': 12,
        'str': 4,
        'dex': 14,
        'con': 10,
        'int': 5,
        'wis': 6,
        'cha': 10,
        'speed': 20,
        'proficiency_bonus': 2,
        'damage_die': '6d6',
        'damage_type': 'acid',        
        'proficient_saves': [],
        'gmnotes': 'https://www.dndbeyond.com/monsters/6143453-shadow-exploder',
        'resistances': ['nmpiercing','nmbludgeoning','nmslashing'],
        'immunities': ['poison','charmed','frightened','deafened','blinded','poisoned','necrotic','prone'],            
    }, 'Shadowmonster': {
        'name': 'Angel?',
        'type': 'aberration',
        'img': '446130444/K7NQB4CSf4aEpautUqrcaw/original.png',
        'hp': 30,
        'ac': 14,
        'str': 14,
        'dex': 6,
        'con': 17,
        'int': 3,
        'wis': 7,
        'cha': 5,
        'speed': 15,
        'proficiency_bonus': 2,
        'proficient_saves': [],
        'resistances': ['nmpiercing','nmbludgeoning','nmslashing','acid'],
        'immunities': ['poison','charmed','frightened','deafened','blinded','poisoned','necrotic','poison'],  
        'gmnotes': 'https://www.dndbeyond.com/monsters/6143729-shadow-broodmonster',
        'endOfTurn': function(me) {
            echo('The... angel...? Whatever it is, it spawned a monster from its body');
            let pos_x = (35 + me.token.get('left'))/70;
            let pos_y = (35 + me.token.get('top'))/70;
            spawnEnemy('Shadowfly', 1, pos_x, pos_y);
        }        
    }, 'Sandshark': {
        'name': 'Sand Shark',
        'type': 'beast',
        'img': '446235449/Ndq2re34rBvcqscNQmEidg/original.png',
        'hp': 124,
        'ac': 17,
        'str': 25,
        'dex': 18,
        'con': 21,
        'int': 2,
        'wis': 10,
        'cha': 5,
        'speed': 50,
        'width': 280,
        'height': 280,
        'proficiency_bonus': 3,
        'proficient_saves': ['str'],
        'attack_stat': 'str', 
        'damage_die': '3d6',
        'damage_type': 'slashing',
        'group_size': 2,
        'tremorsense': true,
        'vision': false,
        'gmnotes': 'https://www.dndbeyond.com/monsters/5580551-sand-shark',
    }, 'Sandshark': {
        'name': 'Sand Shark',
        'type': 'beast',
        'img': '446235449/Ndq2re34rBvcqscNQmEidg/original.png',
        'hp': 124,
        'ac': 17,
        'str': 25,
        'dex': 18,
        'con': 21,
        'int': 2,
        'wis': 10,
        'cha': 5,
        'speed': 50,
        'width': 280,
        'height': 280,
        'proficiency_bonus': 3,
        'proficient_saves': ['str'],
        'attack_stat': 'str', 
        'damage_die': '3d6',
        'damage_type': 'slashing',
        'group_size': 2,
        'tremorsense': true,
        'vision': false,
        'gmnotes': 'https://www.dndbeyond.com/monsters/5580551-sand-shark',
    }, 'Coyote': {
        'name': 'Coyote',
        'type': 'beast',
        'img': '446244048/OOqrvoHQbjzCZ5vNfR_eyg/original.jpg',
        'hp': 7,
        'ac': 12,
        'str': 7,
        'dex': 15,
        'con': 9,
        'int': 3,
        'wis': 12,
        'cha': 8,
        'speed': 50,
        'width': 35,
        'height': 35,
        'proficiency_bonus': 2,
        'proficient_saves': ['dex'],
        'attack_stat': 'dex', 
        'damage_die': '1d4',
        'damage_type': 'piercing',
        'group_size': 5,
        'gmnotes': 'https://www.dndbeyond.com/monsters/5580757-coyote',
    }, 'Drazil': {
        'name': 'Drazil',
        'type': 'beast',
        'img': '446247044/rBGX-0b5jfSLNNGMdz44CQ/original.png',
        'hp': 42,
        'ac': 14,
        'str': 18,
        'dex': 16,
        'con': 17,
        'int': 2,
        'wis': 10,
        'cha': 5,
        'speed': 40,
        'proficiency_bonus': 3,
        'attack_stat': 'str', 
        'damage_die': '1d10',
        'damage_type': 'piercing',
        'group_size': 3,
        'gmnotes': 'https://www.dndbeyond.com/monsters/5141239-drazil',
    }, 'LoviatarCultist': {
        'name': 'Cultist of Loviatar',
        'type': 'humanoid',
        'img': '440803434/li1IfzTrXcCPd0DwYvjjxQ/thumb.png?1747142211',
        'hp': 127,
        'ac': 17,
        'str': 19,
        'dex': 12,
        'con': 18,
        'int': 12,
        'wis': 16,
        'cha': 14,
        'speed': 30,
        'proficiency_bonus': 4,
        'attack_stat': 'str', 
        'damage_die': '1d10',
        'damage_type': 'slashing',
        'group_size': 3,
        'gmnotes': 'https://www.dndbeyond.com/monsters/5471925-cultist-of-loviatar',
    }, 'Bandit': {
        'name': 'Bandit',
        'type': 'humanoid',
        'img': '466228412/MyK5ZlDrutfkBxuZm_TkgQ/original.png',
        'hp': 11,
        'ac': 12,
        'str': 11,
        'dex': 12,
        'con': 12,
        'int': 10,
        'wis': 10,
        'cha': 10,
        'speed': 30,
        'proficiency_bonus': 2,
        'attack_stat': 'dex', 
        'damage_die': '1d8',
        'damage_type': 'piercing',
        'group_size': 4,
        'gmnotes': 'https://www.dndbeyond.com/monsters/16798-bandit',
    }, 'Bountyhunter': {
        'name': 'Bounty Hunter',
        'type': 'humanoid',
        'img': '448718149/czYKKjeOEyWWF9jK0OghZQ/thumb.jpg',
        'hp': 51,
        'ac': 14,
        'str': 10,
        'dex': 16,
        'con': 14,
        'int': 10,
        'wis': 15,
        'cha': 10,
        'speed': 30,
        'proficiency_bonus': 2,
        'attack_stat': 'dex', 
        'damage_die': '2d10',
        'damage_type': 'piercing',
        'group_size': 3,
        'proficient_saves': ['dex','str'],        
        'gmnotes': 'https://www.dndbeyond.com/monsters/5631166-bounty-hunter',
    }, 'zombie_lumberjack': {
        'name': 'Zombie Lumberjack',
        'type': 'undead',
        'img': '448916009/QdfcuITg4Hu2EjqQtrkgjA/original.png',
        'hp': 22,
        'ac': 8,
        'str': 17,
        'dex': 6,
        'con': 16,
        'int': 3,
        'wis': 6,
        'cha': 5,
        'speed': 20,
        'proficiency_bonus': 2,
        'attack_stat': 'str', 
        'damage_die': '1d12',
        'damage_type': 'nmslashing',
        'group_size': 6,
        'proficient_saves': ['wis'],        
        'gmnotes': 'https://roll20.net/compendium/dnd5e/Zombie#content but we are boosting their strength and having them wield a greataxe', 
        'immunities': ['poison','poisoned'],   
        'darkvision': true,
        'turnFunction': async function(me) {
            let target = me.approachPlayer();
            if (target != null) {
                me.basicAttack(target);
            }            
            else me.approachPlayer();
            return target;
        }, 
        'onLethalDamage': async function(me, dmgParams) {
            let dmg = dmgParams['dmg'];
            let isCrit = dmgParams['isCrit'];
            let isRadiant = (dmgParams['dmgType'] == 'radiant');
            if (!isCrit && !isRadiant) {
                let conSave = await rollSave('con', false, false, (5 + Number(dmg)));
                if (conSave) {
                    emphasis(me.get('name') + ' endures the hit with 1 HP');
                    clearMarker(me.token, 'dead');
                    me.token.set({
                        bar3_value: 1
                    });
                    return false;
                }
            } else if (isCrit) {
                emphasis('the critical hit prevents ' + me.get('name') + ' from clinging to its unnatural existence');
            } else if (isRadiant) {
                emphasis('the radiant damage separates the animating force from ' + me.get('name'));
            }
            return true;
        }
    }, 'xorn': {
        'name': 'Xorn',
        'type': 'elemental',
        'img': '450926358/PWWy2LW88zVJ2Q9SJ9ZDDA/thumb.png',
        'hp': 73,
        'ac': 19,
        'str': 17,
        'dex': 10,
        'con': 22,
        'int': 11,
        'wis': 10,
        'cha': 11,
        'speed': 20,
        'proficiency_bonus': 3,
        'attack_stat': 'str', 
        'damage_die': '1d6',
        'damage_type': 'nmslashing',
        'group_size': 2,
        'proficient_saves': [],        
        'gmnotes': 'https://roll20.net/compendium/dnd5e/Xorn#content', 
        'immunities': ['nmpiercing','nmbludgeoning','nmslashing'],   
        'darkvision': true,
        'tremorsense': true
    }, 'giant_ant': {
        'name': 'Giant Ant',
        'type': 'beast',
        'img': '450929244/P3DyptdY_5QfvBduknSw0g/original.png',
        'hp': 26,
        'ac': 15,
        'str': 18,
        'dex': 15,
        'con': 14,
        'int': 1,
        'wis': 15,
        'cha': 3,
        'speed': 30,
        'proficiency_bonus': 2,
        'attack_stat': 'str', 
        'damage_die': '2d4',
        'damage_type': 'nmpiercing',
        'group_size': 2,
        'proficient_saves': ['str'],        
        'gmnotes': 'https://www.dndbeyond.com/monsters/5676379-giant-ant', 
        'immunities': [],   
        'darkvision': true,
        'tremorsense': true
    }, 'giant_ant_queen': {
        'name': 'Giant Ant Queen',
        'type': 'beast',
        'img': '450931319/PBn61GMklKBl43cb0FxhDQ/original.png',
        'hp': 71,
        'ac': 17,
        'str': 21,
        'dex': 15,
        'con': 17,
        'int': 2,
        'wis': 18,
        'cha': 8,
        'speed': 30,
        'proficiency_bonus': 3,
        'attack_stat': 'str', 
        'damage_die': '2d8',
        'damage_type': 'nmpiercing',
        'group_size': 2,
        'proficient_saves': ['str', 'con'],        
        'gmnotes': 'https://www.dndbeyond.com/monsters/5676390-giant-ant-queen', 
        'immunities': [],   
        'darkvision': true,
        'tremorsense': true
    }, 'skeleton': {
        'name': 'Skeleton',
        'type': 'undead',
        'img': '451832226/RV742E7y4rJnj01Cr8AK5Q/thumb.png',
        'hp': 13,
        'ac': 13,
        'str': 10,
        'dex': 14,
        'con': 15,
        'int': 6,
        'wis': 8,
        'cha': 5,
        'speed': 30,
        'proficiency_bonus': 2,
        'attack_stat': 'dex', 
        'damage_die': '1d6',
        'damage_type': 'nmpiercing',
        'group_size': 6,
        'proficient_saves': [],        
        'gmnotes': 'https://roll20.net/compendium/dnd5e/Skeleton#content', 
        'immunities': ['poison','poisoned','exhausted'],   
        'darkvision': true,
        'vulnerabilities': ['bludgeoning']
    }, 'silverstar': {
        'name': 'Silver Star Agent',
        'type': 'humanoid',
        'img': '451331504/l6Fw-PYAVHa64pe7DB2wQQ/thumb.png?1754308942',
        'hp': 51,
        'ac': 14,
        'str': 11,
        'dex': 16,
        'con': 14,
        'int': 10,
        'wis': 15,
        'cha': 10,
        'speed': 30,
        'proficiency_bonus': 2,
        'attack_stat': 'dex', 
        'damage_die': '2d10',
        'damage_type': 'nmpiercing',
        'group_size': 1,
        'proficient_saves': ['str', 'dex'],        
        'gmnotes': 'We will just use the Bounty Hunter statblock here:   https://www.dndbeyond.com/monsters/5631166-bounty-hunter', 
        'immunities': [],   
        'vulnerabilities': []
    }, 'stiriansoldier': {
        'name': 'Stirian Soldier',
        'type': 'humanoid',
        'img': '456770193/eClGBbiw1u8JnAT9fiduYw/thumb.png?1758025279',
        'hp': 57,
        'ac': 15,
        'str': 11,
        'dex': 16,
        'con': 14,
        'int': 13,
        'wis': 13,
        'cha': 10,
        'speed': 30,
        'proficiency_bonus': 3,
        'attack_stat': 'dex', 
        'damage_die': '1d8',
        'damage_type': 'nmpiercing',
        'group_size': 5,
        'proficient_saves': ['int', 'dex', 'con'],        
        'gmnotes': 'https://www.dndbeyond.com/monsters/5793546-stirian-soldier', 
        'immunities': [],   
        'vulnerabilities': [],
        'resistances': ['cold']
    }, 'Kytherian Clockwork Soldier': {
        'name': 'Clockwork Soldier',
        'type': 'construct',        
        'img': '459477481/I3G6Wh9vgERLzMeo6kIXAw/max.png?1759927943',
        'hp': 187,
        'ac': 18,
        'str': 18,
        'dex': 22,
        'con': 19,
        'int': 6,
        'wis': 10,
        'cha': 10,
        'speed': 50,
        'width': 140,
        'height': 140,        
        'attack_stat': 'dex',
        'proficiency_bonus': 4,
        'damage_die': '2d6',
        'damage_type': 'slashing',
        'gmnotes': 'https://www.dndbeyond.com/monsters/5850569-kytherian-clockwork-soldier', 
        'proficient_saves': ['str', 'dex', 'con'],
        'resistances': [],
        'immunities': ['psychic', 'poison', 'exhaustion', 'poisoned'],
        'vulnerabilities': [],
        'group_size': 1,        
        'rechargeDie': '1d6',
        'rechargeNumber': 5,
        'rechargeAbilityReady': true,
        'reach': 10,
        'startOfTurnTrait': function(me,token) {
            whisper(getObj('player', getGM()).get('displayname'), 'roll to recharge ability if necessary');
        }        
    }, 'Scarebear': {
        'name': 'Scarebear',
        'type': 'humanoid',
        'img': '460311062/WgeJWgGZ1QZAEZNt-Qcr8g/max.png?1760481532',
        'hp': 55,
        'ac': 15,
        'str': 22,
        'dex': 17,
        'con': 20,
        'int': 2,
        'wis': 14,
        'cha': 7,
        'speed': 40,
        'proficiency_bonus': 3,
        'attack_stat': 'str', 
        'damage_die': '1d8',
        'damage_type': 'slashing',
        'group_size': 1,
        'proficient_saves': [],        
        'gmnotes': 'https://www.dndbeyond.com/monsters/5866942-scarebear', 
        'immunities': ['blinded','charmed','deafened','poisoned','frightened'],   
        'vulnerabilities': [],
        'resistances': ['cold','poison'],
        'magicResistance': true,
    }, 'Bodak': {
        'name': 'Bodak',
        'type': 'undead',
        'img': '462498210/aL8SVGBwhDtdNhJ4USDO8w/thumb.png',
        'hp': 58,
        'ac': 15,
        'str': 15,
        'dex': 16,
        'con': 15,
        'int': 7,
        'wis': 12,
        'cha': 12,
        'speed': 30,
        'proficiency_bonus': 3,
        'attack_stat': 'str', 
        'damage_die': '1d4',
        'damage_type': 'nmbludgeoning',
        'secondary_damage_die': '2d8',
        'secondary_damage_type': 'necrotic',        
        'group_size': 1,
        'proficient_saves': [],        
        'gmnotes': 'http://dndroll.wikidot.com/creatures:bodak', 
        'immunities': ['lightning','poison','charmed','frightened','poisoned'],   
        'vulnerabilities': [],
        'resistances': ['cold','fire','necrotic','nmbludgeoning','nmslashing','nmpiercing'],
    }, 'Banshee': {
        'name': 'Banshee',
        'type': 'undead',
        'img': '462499829/nUQPOAdff34uSXHYozNz6Q/thumb.png',
        'hp': 58,
        'ac': 12,
        'str': 1,
        'dex': 14,
        'con': 10,
        'int': 12,
        'wis': 11,
        'cha': 17,
        'speed': 40,
        'proficiency_bonus': 2,
        'attack_stat': 'dex', 
        'damage_die': '3d6',
        'damage_type': 'necrotic',
        'group_size': 1,
        'proficient_saves': ['wis','cha'],        
        'gmnotes': 'https://www.dndbeyond.com/monsters/17089-banshee?srsltid=AfmBOoqPc-HhtOiTJveSZT18Ou2KoqgBpsq_LInJuZchuT_Z0NsepuG6', 
        'immunities': ['cold','necrotic','poison','charmed','frightened','poisoned','exhausted','grappled','paralyzed','petrified','prone','restrained'],   
        'vulnerabilities': [],
        'resistances': ['acid','fire','lightning','thunder','nmbludgeoning','nmslashing','nmpiercing'],
    }, 'Gibbering Mouther': {
        'name': 'Gibbering Mouther',
        'type': 'aberration',
        'img': '462501099/sb4oUSEQPpyrnM9ZQsNRZg/original.png',
        'hp': 52,
        'ac': 9,
        'str': 10,
        'dex': 8,
        'con': 16,
        'int': 3,
        'wis': 10,
        'cha': 6,
        'speed': 20,
        'aura1_radius': 10,
        'aura2_radius': 20,
        'proficiency_bonus': 2,
        'attack_stat': 'str', 
        'damage_die': '2d6',
        'damage_type': 'piercing',
        'group_size': 1,
        'proficient_saves': [],        
        'gmnotes': 'https://roll20.net/compendium/dnd5e/Gibbering%20Mouther', 
        'immunities': ['prone'],   
        'vulnerabilities': [],
        'resistances': [],
    }, 'Creepy Crawly': {
        'name': 'Creepy Crawly',
        'type': 'aberration',
        'img': '462794647/o_FxJGKkS0WZzm7ITwNwaQ/original.png',
        'hp': 49,
        'ac': 17,
        'str': 13,
        'dex': 20,
        'con': 20,
        'int': 2,
        'wis': 17,
        'cha': 2,
        'speed': 40,
        'proficiency_bonus': 3,
        'attack_stat': 'dex', 
        'damage_die': '1d6',
        'damage_type': 'slashing',
        'group_size': 1,
        'proficient_saves': [],        
        'gmnotes': 'https://www.dndbeyond.com/monsters/5919557-creepy-crawly', 
        'immunities': ['blinded','charmed','deafened','poisoned','frightened'],   
        'vulnerabilities': [],
        'resistances': ['cold','poison'],
        'magicResistance': true,
    }, 'Mummy': {
        'name': 'Mummy',
        'type': 'undead',
        'img': '460301508/QDfivhx6UOseWykcI18Gvw/max.png?1760475780',
        'hp': 58,
        'ac': 11,
        'str': 16,
        'dex': 8,
        'con': 15,
        'int': 6,
        'wis': 10,
        'cha': 12,
        'speed': 20,
        'proficiency_bonus': 2,
        'attack_stat': 'str', 
        'damage_die': '2d6',
        'damage_type': 'bludgeoning',
        'secondary_damage_die': '3d6',
        'secondary_damage_type': 'necrotic',          
        'group_size': 2,
        'proficient_saves': [],        
        'gmnotes': 'https://www.dndbeyond.com/monsters/16961-mummy', 
        'immunities': ['necrotic','poison','charmed','exhaustion','poisoned','paralyzed','frightened'],   
        'vulnerabilities': ['fire'],
        'resistances': ['nmbludgeoning','nmslashing','nmpiercing']
    }, 'AnimatedArmor': {
        'name': 'Animated Armor',
        'type': 'construct',
        'img': '465285492/AjRhX_lho-mNKwpHX-JZwA/original.png',
        'hp': 33,
        'ac': 18,
        'str': 14,
        'dex': 11,
        'con': 13,
        'int': 1,
        'wis': 3,
        'cha': 1,
        'speed': 25,
        'proficiency_bonus': 2,
        'attack_stat': 'str', 
        'damage_die': '1d6',
        'damage_type': 'bludgeoning',
        'group_size': 2,
        'proficient_saves': [],        
        'gmnotes': 'https://www.dndbeyond.com/monsters/16786-animated-armor', 
        'immunities': ['psychic','poison','blinded','deafened','charmed','exhaustion','poisoned','paralyzed','frightened','petrified'],   
        'vulnerabilities': [],
        'resistances': []
    }, 'FlyingSword': {
        'name': 'Flying Sword ',
        'type': 'construct',
        'img': '465286324/5cunw3MArwEnGa5Lf23Sug/original.png',
        'hp': 17,
        'ac': 17,
        'str': 12,
        'dex': 15,
        'con': 11,
        'int': 1,
        'wis': 5,
        'cha': 1,
        'speed': 50,
        'proficiency_bonus': 2,
        'attack_stat': 'str', 
        'damage_die': '1d8',
        'damage_type': 'slashing',
        'group_size': 2,
        'proficient_saves': [],        
        'gmnotes': 'https://www.dndbeyond.com/monsters/16865-flying-sword', 
        'immunities': ['psychic','poison','blinded','deafened','charmed','poisoned','paralyzed','frightened','petrified'],   
        'vulnerabilities': [],
        'resistances': []
    }, 'HelmedHorror': {
        'name': 'Helmed Horror',
        'type': 'construct',
        'img': '397876055/qsZqjXLB_7W-Gxq7HVP8hQ/max.png?1718994938',
        'hp': 60,
        'ac': 20,
        'str': 18,
        'dex': 13,
        'con': 16,
        'int': 10,
        'wis': 10,
        'cha': 10,
        'speed': 30,        
        'proficiency_bonus': 2,
        'attack_stat': 'str', 
        'damage_die': '1d10',
        'damage_type': 'nmslashing',
        'group_size': 1,
        'proficient_saves': [],        
        'gmnotes': 'https://5e.tools/bestiary/helmed-horror-mm.html', 
        'immunities': ['force','necrotic','poison','charmed','blinded','deafened','poisoned','paralyzed','frightened','petrified','stunned'],   
        'vulnerabilities': [],
        'resistances': ['nmbludgeoning','nmslashing','nmpiercing'],
        'magicResistance': true,
    }, 'ZombieRatSwarm': {
        'name': 'Swarm of Undead Rats',
        'type': 'undead',
        'img': '465459927/HUfUrjc4rf8RXBUR8eZXPw/max.png?1764025791',
        'hp': 24,
        'ac': 10,
        'str': 9,
        'dex': 11,
        'con': 9,
        'int': 2,
        'wis': 10,
        'cha': 3,
        'speed': 20,        
        'proficiency_bonus': 2,
        'attack_stat': 'dex', 
        'damage_die': '2d6',
        'damage_type': 'piercing',
        'secondary_damage_die': '2',
        'secondary_damage_type': 'necrotic',         
        'group_size': 1,
        'proficient_saves': [],        
        'gmnotes': 'https://www.dndbeyond.com/monsters/5977355-swarm-of-undead-rats', 
        'immunities': ['charmed','grappled','prone','frightened','petrified','paralyzed','restrained','stunned'],   
        'vulnerabilities': [],
        'resistances': ['nmbludgeoning','nmslashing','nmpiercing','necrotic','poison'],        
    }, 'Rametekh': {
        'name': 'Pharaoh Rametekh',
        'type': 'undead',
        'img': '467545975/cHDHonGzKfN6qZ6OC2sTsw/original.png',
        'hp': 98,
        'ac': 16,
        'str': 18,
        'dex': 10,
        'con': 17,
        'int': 14,
        'wis': 18,
        'cha': 16,
        'speed': 20,
        'proficiency_bonus': 3,
        'attack_stat': 'str', 
        'damage_die': '2d6',
        'damage_type': 'bludgeoning',
        'secondary_damage_die': '2d6',
        'secondary_damage_type': 'necrotic',          
        'group_size': 2,
        'proficient_saves': ['wis'],        
        'gmnotes': 'https://www.dndbeyond.com/monsters/5977254-pharaoh-rametekh', 
        'immunities': ['necrotic','poison','charmed','exhaustion','poisoned','paralyzed','frightened'],   
        'vulnerabilities': ['fire'],
        'resistances': ['nmbludgeoning','nmslashing','nmpiercing']
    }, 'Mimic': {
        'name': 'Mimic',
        'type': 'monstrosity',
        'img': '467670482/FHYOyYwumWeIzi1KrhSqng/original.png',
        'hp': 58,
        'ac': 12,
        'str': 17,
        'dex': 12,
        'con': 15,
        'int': 5,
        'wis': 13,
        'cha': 8,
        'speed': 15,
        'proficiency_bonus': 2,
        'attack_stat': 'str', 
        'damage_die': '1d8',
        'damage_type': 'bludgeoning',      
        'group_size': 1,
        'proficient_saves': [],        
        'gmnotes': 'https://www.dndbeyond.com/monsters/16957-mimic', 
        'immunities': ['acid','prone'],   
        'vulnerabilities': [],
        'resistances': []
    }, 'Cyclops': {
        'name': 'Cyclops',
        'type': 'giant',
        'img': '472739566/dqxr7_Z5iMpI7aIKCay0Sw/original.png',
        'width': 210,
        'height': 210,
        'hp': 138,
        'ac': 14,
        'str': 22,
        'dex': 11,
        'con': 20,
        'int': 8,
        'wis': 6,
        'cha': 10,
        'speed': 30,
        'proficiency_bonus': 3,
        'attack_stat': 'str', 
        'damage_die': '3d8',
        'damage_type': 'bludgeoning',      
        'group_size': 1,
        'proficient_saves': [],        
        'gmnotes': 'https://www.dndbeyond.com/monsters/17090-cyclops', 
        'immunities': [],   
        'vulnerabilities': [],
        'resistances': []
    }, 'Hydra': {
        'name': 'Hydra',
        'type': 'monstrosity',
        'img': '472739564/RUoV-J38FCYtcjKmBoFi2Q/original.png',
        'width': 210,
        'height': 210,
        'hp': 172,
        'ac': 15,
        'str': 20,
        'dex': 12,
        'con': 20,
        'int': 2,
        'wis': 10,
        'cha': 7,
        'speed': 30,
        'proficiency_bonus': 3,
        'attack_stat': 'str', 
        'damage_die': '1d10',
        'damage_type': 'bludgeoning',      
        'group_size': 1,
        'proficient_saves': [],        
        'gmnotes': 'https://www.dndbeyond.com/monsters/16929-hydra', 
        'immunities': [],   
        'vulnerabilities': [],
        'resistances': ['blinded','charmed','deafened','frightened','stunned','unconscious']
    }, 'Lamia': {
        'name': 'Lamia',
        'type': 'monstrosity',
        'img': '472739565/dzmPXoSBilq47lm-JjT8lA/original.png',
        'width': 140,
        'height': 140,
        'hp': 97,
        'ac': 13,
        'str': 16,
        'dex': 13,
        'con': 15,
        'int': 14,
        'wis': 15,
        'cha': 16,
        'speed': 30,
        'darkvision': true,
        'proficiency_bonus': 2,
        'attack_stat': 'str', 
        'damage_die': '2d10',
        'damage_type': 'slashing',      
        'group_size': 1,
        'proficient_saves': [],        
        'gmnotes': 'https://www.dndbeyond.com/monsters/16941-lamia', 
        'immunities': [],   
        'vulnerabilities': [],
        'resistances': []
    }, 'Chimera': {
        'name': 'Chimera',
        'type': 'monstrosity',
        'img': '472739568/gVH3uNoaFYMqHoXEQ6M2Bw/original.png',
        'width': 140,
        'height': 140,
        'hp': 114,
        'ac': 14,
        'str': 19,
        'dex': 11,
        'con': 19,
        'int': 3,
        'wis': 14,
        'cha': 10,
        'speed': 60,
        'darkvision': true,
        'proficiency_bonus': 3,
        'attack_stat': 'str', 
        'damage_die': '2d6',
        'damage_type': 'slashing',      
        'group_size': 1,
        'proficient_saves': [],        
        'gmnotes': 'https://www.dndbeyond.com/monsters/16941-lamia', 
        'immunities': [],   
        'vulnerabilities': [],
        'resistances': []
    }, 'Earth Myrmidon': {
        'name': 'Earth Myrmidon',
        'type': 'monstrosity',
        'img': '472739567/3iXB9OJRfQDd7DHkZk7SEg/original.jpg',
        'width': 70,
        'height': 70,
        'hp': 127,
        'ac': 18,
        'str': 18,
        'dex': 10,
        'con': 17,
        'int': 8,
        'wis': 10,
        'cha': 10,
        'speed': 30,
        'darkvision': true,
        'proficiency_bonus': 3,
        'attack_stat': 'str', 
        'damage_die': '2d6',
        'damage_type': 'slashing',      
        'group_size': 2,
        'proficient_saves': [],        
        'gmnotes': 'http://dndroll.wikidot.com/creatures:earth-elemental-myrmidon', 
        'immunities': ['poison','poisoned','paralyzed','petrified','prone'],   
        'vulnerabilities': [],
        'resistances': ['nmbludgeoning','nmpiercing','nmslashing']
    }, 'Abby Daniels': {
        'name': 'Abby "The Adder" Daniels',
        'type': 'humanoid',
        'img': '432325032/FLzzlCteovancA9V47ktAg/max.jpg?1741635391',
        'width': 70,
        'height': 70,
        'hp': 189,
        'ac': 14,
        'str': 23,
        'dex': 10,
        'con': 18,
        'int': 8,
        'wis': 8,
        'cha': 16,
        'speed': 50,
        'proficiency_bonus':5,
        'attack_stat': 'str', 
        'damage_die': '1d12',
        'damage_type': 'bludeoning',      
        'group_size': 1,
        'proficient_saves': ['str','dex','wis','cha'],        
        'gmnotes': 'http://dndroll.wikidot.com/creatures:earth-elemental-myrmidon', 
        'immunities': ['poison','poisoned','paralyzed','petrified','prone'],   
        'vulnerabilities': [],
        'resistances': ['nmbludgeoning','nmpiercing','nmslashing']
    }, 'Payaan': {
        'name': 'Payaan, Origos Zealot',
        'type': 'humanoid',
        'img': '472746218/rwhM_MyaayZsYmxLIJ2_GQ/max.png?1769178937',
        'hp': 122,
        'ac': 17,
        'str': 13,
        'dex': 12,
        'con': 16,
        'int': 11,
        'wis': 19,
        'cha': 17,
        'speed': 30,
        'adv_on_concentration_checks': true,
        'proficiency_bonus':4,
        'attack_stat': 'str', 
        'damage_die': '1d8',
        'damage_type': 'slashing',      
        'group_size': 1,
        'proficient_saves': ['con','wis','cha'],        
        'gmnotes': 'https://www.dndbeyond.com/monsters/6143145-payaan-origos-zealot', 
        'immunities': ['charmed','frightened'],   
        'vulnerabilities': [],
        'resistances': []        
    }, 'Centurion': {
        'name': 'Centurion',
        'type': 'humanoid',
        'img': '472786318/iE3ZshT44M4ZCl8efdBPHA/original.png',
        'hp': 43,
        'ac': 17,
        'str': 16,
        'dex': 13,
        'con': 14,
        'int': 10,
        'wis': 11,
        'cha': 10,
        'speed': 30,
        'proficiency_bonus':3,
        'attack_stat': 'str', 
        'damage_die': '1d8',
        'damage_type': 'slashing',      
        'group_size': 3,
        'proficient_saves': ['str','con'],        
        'gmnotes': 'https://www.dndbeyond.com/monsters/6143911-agrimanian-centurion', 
        'immunities': [],   
        'vulnerabilities': [],
        'resistances': []        
    }, 'Cultist': {
        'name': 'Cultist',
        'type': 'humanoid',
        'img': '472797229/vNjeokxlX_V8h2Pv39Pt0g/original.png',
        'hp': 33,
        'ac': 13,
        'str': 11,
        'dex': 14,
        'con': 12,
        'int': 10,
        'wis': 13,
        'cha': 14,
        'speed': 30,
        'proficiency_bonus':3,
        'attack_stat': 'dex', 
        'damage_die': '1d4',
        'damage_type': 'nmpiercing',      
        'group_size': 3,
        'proficient_saves': [],        
        'gmnotes': 'https://roll20.net/compendium/dnd5e/Cult%20Fanatic#content', 
        'immunities': [],   
        'vulnerabilities': [],
        'resistances': ['charmed','frightened']        
    }, 'zombie_gladiator': {
        'name': 'Zombie Gladiator',
        'type': 'undead',
        'img': '474241702/rSOid9xrydrNTQXFp6G1iw/original.png',
        'hp': 22,
        'ac': 8,
        'str': 17,
        'dex': 6,
        'con': 16,
        'int': 3,
        'wis': 6,
        'cha': 8,
        'speed': 20,
        'proficiency_bonus': 2,
        'attack_stat': 'str', 
        'damage_die': '1d10',
        'damage_type': 'nmslashing',
        'group_size': 3,
        'proficient_saves': ['wis'],        
        'gmnotes': 'https://roll20.net/compendium/dnd5e/Zombie#content but we are boosting their strength and cha, and having them wield a trident (1d10/1d8) and net they can use as a bonus action. Net rules: https://www.dndbeyond.com/equipment/38-net?srsltid=AfmBOoons-Z0un6KWEQ0zWvC9PlQe4rNLq0_CeGhBN6Ry9bM5tJVHQu-', 
        'immunities': ['poison','poisoned'],   
        'darkvision': true,
        'onLethalDamage': async function(me, dmgParams) {
            let dmg = dmgParams['dmg'];
            let isCrit = dmgParams['isCrit'];
            let isRadiant = (dmgParams['dmgType'] == 'radiant');
            if (!isCrit && !isRadiant) {
                let conSave = await rollSave('con', false, false, (5 + Number(dmg)));
                if (conSave) {
                    emphasis(me.get('name') + ' endures the hit with 1 HP');
                    clearMarker(me.token, 'dead');
                    me.token.set({
                        bar3_value: 1
                    });
                    return false;
                }
            } else if (isCrit) {
                emphasis('the critical hit prevents ' + me.get('name') + ' from clinging to its unnatural existence');
            } else if (isRadiant) {
                emphasis('the radiant damage separates the animating force from ' + me.get('name'));
            }
            return true;
        }
    }, 'kheper_1': {
        'name': 'Kheper, Holding Back',
        'type': 'humanoid',
        'img': '474242354/XkbHfXEIH20zAFWinVlSSg/original.png',
        'hp': 223,
        'ac': 15,
        'str': 19,
        'dex': 15,
        'con': 16,
        'int': 8,
        'wis': 9,
        'cha': 13,
        'speed': 30,
        'width': 140,
        'height': 140,
        'proficiency_bonus': 3,
        'attack_stat': 'str', 
        'damage_die': '1d8',
        'damage_type': 'nmbludgeoning',
        'proficient_saves': ['str','con','dex'],        
        'gmnotes': 'https://www.dndbeyond.com/monsters/6175490-kheper-holding-back', 
        'immunities': [],   
    }, 'catulla_1': {
        'name': 'Catulla, Focused on the Mission',
        'type': 'humanoid',
        'img': '474244609/HkdX0V8WK8_e10TzDObvRA/original.png',
        'hp': 143,
        'ac': 14,
        'str': 9,
        'dex': 13,
        'con': 16,
        'int': 19,
        'wis': 12,
        'cha': 18,
        'speed': 30,
        'proficiency_bonus': 3,
        'casterLevel': 9,
        'spell_save_dc': 15,
        'proficient_saves': ['int','wis'],        
        'gmnotes': 'https://www.dndbeyond.com/monsters/6175541-catulla-focused-on-the-mission', 
        'immunities': [],
        'resistances': ['necrotic'],
    }, 'krug_simulacrum': {
        'name': 'Krug Spinecrusher',
        'type': 'humanoid',
        'img': '474249922/ieYQ9hYEJGxv6BVqDckIAw/original.png',
        'hp': 177,
        'ac': 14,
        'str': 19,
        'dex': 17,
        'con': 20,
        'int': 7,
        'wis': 9,
        'cha': 15,
        'speed': 40,
        'proficiency_bonus': 5,
        'proficient_saves': ['str','con'],        
        'gmnotes': 'https://www.dndbeyond.com/monsters/6175588-krug-simulacrum', 
        'immunities': ['charmed','frightened'],
        'resistances': ['nmbludgeoning','nmpiercing','nmslashing'],
    }, 'medusa': {
        'name': 'Medusa',
        'type': 'monstrosity',
        'img': '474729069/coxaOrb2rJo6clql8J5ktg/original.png',
        'hp': 127,
        'ac': 15,
        'str': 10,
        'dex': 15,
        'con': 16,
        'int': 12,
        'wis': 13,
        'cha': 15,
        'speed': 30,
        'darkvision': true,
        'proficiency_bonus': 3,
        'proficient_saves': [],        
        'gmnotes': 'https://www.dndbeyond.com/monsters/16954-medusa', 
        'immunities': [],
        'resistances': [],
    }, 'Mind Flayer': {
        'name': 'WTF?',
        'type': 'aberration',
        'img': '477505898/XTkTchSLbpY2G4h22pgbHw/max.png?1772154134',
        'hp': 71,
        'ac': 15,
        'str': 11,
        'dex': 12,
        'con': 12,
        'int': 19,
        'wis': 17,
        'cha': 17,
        'speed': 30,
        'darkvision': true,
        'proficiency_bonus': 3,
        'proficient_saves': ['int','wis','cha'],        
        'gmnotes': 'http://dndroll.wikidot.com/creatures:mind-flayer', 
        'immunities': [],
        'resistances': [],
        'magicResistance': true,        
    }, 'Pallas': {
        'name': 'Pallas',
        'type': 'humanoid',
        'img': '477505695/CtkQWT9MANnHBmEIQQKaYA/original.png',
        'hp': 34,
        'ac': 11,
        'str': 9,
        'dex': 12,
        'con': 11,
        'int': 21,
        'wis': 17,
        'cha': 13,
        'speed': 30,
        'proficiency_bonus': 3,
        'proficient_saves': ['int'],        
        'gmnotes': 'https://www.dndbeyond.com/monsters/6248617-pallas', 
        'immunities': [],
        'resistances': [],
        'magicResistance': true,        
    }, 'Homunculus': {
        'name': 'Homunculus',
        'type': 'Construct',
        'img': '477587741/nbKnMpXgB2Oa5niWTHGcPQ/original.png',
        'hp': 5,
        'ac': 13,
        'str': 4,
        'dex': 15,
        'con': 11,
        'int': 10,
        'wis': 10,
        'cha': 7,
        'speed': 40,
        'darkvision': true,
        'proficiency_bonus': 2,
        'width': 17.5,
        'height': 17.5,
        'gmnotes': 'https://www.dndbeyond.com/monsters/16926-homunculus', 
        'immunities': ['poison','poisoned','charmed'],
        'resistances': [],
    }
}
