var mycustomfx = {
        'thunderwave': {
	        "angle": -1,
        	"angleRandom": 45,
        	"duration": 25,
        	"emissionRate": 25,
        	"lifeSpan": 5,
        	"lifeSpanRandom": 0,
        	"maxParticles": 750,
        	"size": 20,
        	"sizeRandom": 10,
        	"speed": 30,
        	"speedRandom": 3,
        	"startColour":		[50, 50, 50, 0.5],
            "startColourRandom":	[150, 150, 150, 0.25],
            "endColour":		[128, 128, 128, 0],
            "endColourRandom":	[125, 125, 125, 0]
        },
        'eldritchblast': {
        	"angle": 270,
        	"angleRandom": 360,
        	"duration": 4,
        	"emissionRate": 100,
        	"endColour": [0, 15, 0, 0],
        	"endColourRandom": [0, 20, 10, 0],
        	"gravity": {"x":0.01, "y":0.65},
        	"lifeSpan": 5,
        	"lifeSpanRandom": 2,
        	"maxParticles": 350,
        	"sharpness": 100,
        	"sharpnessRandom": 0,
        	"size": 8,
        	"sizeRandom": 3,
        	"speed": 10,
        	"speedRandom": 1.5,
        	"startColour": [0, 40, 40, 0.5],
        	"startColourRandom": [0, 30, 10, 0]
        },
        'illusionarydart': {
        	"angle": 270,
        	"angleRandom": 360,
        	"duration": 4,
        	"emissionRate": 100,
        	"endColour": [95, 64, 127, 0],
        	"endColourRandom": [10, 10, 10, 0],
        	"gravity": {"x":0.01, "y":0.65},
        	"lifeSpan": 5,
        	"lifeSpanRandom": 2,
        	"maxParticles": 350,
        	"sharpness": 100,
        	"sharpnessRandom": 0,
        	"size": 8,
        	"sizeRandom": 3,
        	"speed": 10,
        	"speedRandom": 1.5,
        	"startColour": [190, 127, 255, 0.5],
        	"startColourRandom": [10, 10, 10, 0]
        },        
        'shield': {
            "maxParticles": 200,
            "size": 100,
            "sizeRandom": 0,
            "lifeSpan": 10,
            "lifeSpanRandom": 0,
            "emissionRate": 2,
            "speed": 0,
            "speedRandom": 0,
            "gravity": {"x":0.0001, "y":0.0001},
            "angle": 0.0,
            "angleRandom": 360,
            "startColour": [10, 10, 50, 0],
            "startColourRandom": [10, 10, 10, 0],
            "endColour": [10, 10, 50, 1],
            "endColourRandom": [10,10,10,0],
            "sharpness": 55,
            "sharpnessRandom": 40
        },
        'createwater': {
	        "angle": -1,
        	"angleRandom": 45,
        	"duration": 25,
        	"emissionRate": 25,
        	"lifeSpan": 10,
        	"lifeSpanRandom": 0,
        	"maxParticles": 750,
        	"size": 20,
        	"sizeRandom": 10,
        	"speed": 30,
        	"speedRandom": 3,
            "startColour":		[15, 15, 150, 1],
            "startColourRandom":	[5, 5, 25, 0.25],
            "endColour":		[10, 10, 100, 0],
            "endColourRandom":	[10, 10, 25, 0]
        },
        'hypnoticpattern': {
	        "angle": -1,
        	"angleRandom": 45,
        	"duration": 25,
        	"emissionRate": 25,
        	"lifeSpan": 10,
        	"lifeSpanRandom": 0,
        	"maxParticles": 750,
        	"size": 20,
        	"sizeRandom": 10,
        	"speed": 30,
        	"speedRandom": 3,
            "startColour":		[15, 15, 150, 1],
            "startColourRandom":	[5, 5, 25, 0.25],
            "endColour":		[10, 10, 100, 0],
            "endColourRandom":	[10, 10, 25, 0]
        },
        'shockinggrasp': {
        	"angle": 0,
        	"angleRandom": 360,
        	"duration": 1,
        	"emissionRate": 5000,
        	"endColour": [0, 10, 50, 0],
        	"endColourRandom": [0, 0, 0, 0],
        	"gravity": {"x":0.01, "y":0.01},
        	"lifeSpan": 1,
        	"lifeSpanRandom": 0,
        	"maxParticles": 5000,
        	"size": 10,
        	"sizeRandom": 0,
        	"speed": 10,
        	"speedRandom": 1,
        	"startColour": [90, 125, 250, 1],
        	"startColourRandom": [12, 12, 12, 1]
        },
        'catapult': {
        	"angle": -1,
        	"angleRandom": 0,
        	"duration": 29,
        	"emissionRate": 29,
        	"endColour": [64, 64, 64, 0.5],
        	"endColourRandom": [0, 0, 0, 0],
        	"lifeSpan": 30,
        	"lifeSpanRandom": 0,
        	"maxParticles": 1,
        	"size": 50,
        	"sizeRandom": 0,
        	"speed": 30,
        	"speedRandom": 0,
        	"startColour": [64, 64, 65, 1],
        	"startColourRandom": [0, 0, 0, 0]
        },
        'hex': {
        	"angle": 360,
        	"angleRandom": 360,
        	"duration": 35,
        	"emissionRate": 10,
        	"endColour": [40, 15, 40, 0],
        	"endColourRandom": [10, 0, 10, 0],
        	"gravity": {"x":0.1, "y":0.1},
        	"lifeSpan": 5,
        	"lifeSpanRandom": 7,
        	"maxParticles": 350,
        	"sharpness": 40,
        	"sharpnessRandom": 10,
        	"size": 20,
        	"sizeRandom": 5,
        	"speed": 5,
        	"speedRandom": 1.5,
        	"startColour": [160, 65, 160, 0.5],
        	"startColourRandom": [20, 0, 20, 0.1]
        },
        'hailofthorns': {
        	"angle": 360,
        	"angleRandom": 360,
        	"duration": 10,
        	"emissionRate": 10,
        	"endColour": [0, 15, 15, 0],
        	"endColourRandom": [0, 10, 5, 0],
        	"lifeSpan": 12,
        	"lifeSpanRandom": 0,
        	"maxParticles": 100,
        	"sharpness": 70,
        	"sharpnessRandom": 0,
        	"size": 15,
        	"sizeRandom": 5,
        	"speed": 8,
        	"speedRandom": 1.5,
        	"startColour": [0, 50, 32, 0.5],
        	"startColourRandom": [0, 20, 10, 0.1]
        },
        'witherandbloom':         {
        	"angle": 360,
        	"angleRandom": 360,
        	"duration": 35,
        	"emissionRate": 10,
        	"endColour": [0, 15, 0, 0],
        	"endColourRandom": [0, 20, 10, 0],
        	"gravity": {"x":0.1, "y":0.1},
        	"lifeSpan": 25,
        	"lifeSpanRandom": 7,
        	"maxParticles": 350,
        	"sharpness": 40,
        	"sharpnessRandom": 10,
        	"size": 40,
        	"sizeRandom": 5,
        	"speed": 5,
        	"speedRandom": 1.5,
        	"startColour": [0, 40, 20, 0.5],
        	"startColourRandom": [0, 30, 10, 0]
        },
        'faeriefire1': {
	        "angle": -1,
        	"angleRandom": 45,
        	"duration": 25,
        	"emissionRate": 25,
        	"lifeSpan": 7,
        	"lifeSpanRandom": 0,
        	"maxParticles": 250,
        	"size": 20,
        	"sizeRandom": 10,
        	"speed": 30,
        	"speedRandom": 3,
			"startColour":		[90, 90, 175, 1],
			"startColourRandom":	[0, 0, 0, 0.25],
			"endColour":		[125, 125, 255, 0],
			"endColourRandom":	[0, 0, 0, 0]
        },		
        'faeriefire2': {
	        "angle": -1,
        	"angleRandom": 45,
        	"duration": 25,
        	"emissionRate": 25,
        	"lifeSpan": 7,
        	"lifeSpanRandom": 0,
        	"maxParticles": 250,
        	"size": 20,
        	"sizeRandom": 10,
        	"speed": 30,
        	"speedRandom": 3,
			"startColour":		[0, 250, 50, 1],
			"startColourRandom":	[0, 20, 10, 0.25],
			"endColour":		[0, 250, 50, 0],
			"endColourRandom":	[20, 20, 20, 0]
        },		
        'faeriefire3': {
	        "angle": -1,
        	"angleRandom": 45,
        	"duration": 25,
        	"emissionRate": 25,
        	"lifeSpan": 7,
        	"lifeSpanRandom": 0,
        	"maxParticles": 250,
        	"size": 20,
        	"sizeRandom": 10,
        	"speed": 30,
        	"speedRandom": 3,
			"startColour":		[200, 40, 150, 1],
			"startColourRandom":	[25, 5, 20, 0.25],
			"endColour":		[200, 40, 150, 0],
			"endColourRandom":	[50, 10, 40, 0]
        },		
        'lightningBolt': {
        	"angle": -1,
        	"angleRandom": 0.5,
        	"duration": 1,
        	"emissionRate": 5000,
        	"endColour": [0, 10, 50, 0],
        	"endColourRandom": [0, 0, 0, 0],
        	"gravity": {"x":0.01, "y":0.01},
        	"lifeSpan": 6,
        	"lifeSpanRandom": 1,
        	"maxParticles": 5000,
        	"size": 10,
        	"sizeRandom": 0,
        	"speed": 120,
        	"speedRandom": 121,
        	"startColour": [90, 125, 250, 1],
        	"startColourRandom": [12, 12, 12, 1]
        },
        'slow': {
        	"angle": -1,
        	"angleRandom": 45,
        	"duration": 25,
        	"emissionRate": 25,
        	"endColour": [150, 150, 200, 1],
        	"endColourRandom": [5, 10, 15, 0.25],
        	"lifeSpan": 12,
        	"lifeSpanRandom": 0,
        	"maxParticles": 750,
        	"size": 20,
        	"sizeRandom": 10,
        	"speed": 30,
        	"speedRandom": 3,
        	"startColour": [150, 150, 200, 1],
        	"startColourRandom": [5, 10, 15, 0.25]
        },
        'iceStorm': {
        	"angle": 0,
        	"angleRandom": 360,
        	"duration": -1,
        	"emissionRate": 100,
        	"endColour": [125, 125, 255, 0],
        	"endColourRandom": [0, 0, 0, 0],
        	"gravity": {"x":0.01, "y":0.01},
        	"lifeSpan": 10,
        	"lifeSpanRandom": 0,
        	"maxParticles": 500,
        	"size": 20,
        	"sizeRandom": 4,
        	"speed": 30,
        	"speedRandom": 1.5,
        	"startColour": [90, 90, 175, 1],
        	"startColourRandom": [0, 0, 0, 0.25]
        },
        'sickeningRadiance': {
        	"maxParticles": 100,
        	"emissionRate": 4,
        	"size": 250,
        	"sizeRandom": 10,
        	"lifeSpan": 15,
        	"lifeSpanRandom": 0,
        	"speed": 25,
        	"speedRandom": 1.5,
        	"gravity": {"x":0.01, "y":0.01},
        	"angle": 0,
        	"angleRandom": 360,
        	"duration": 100,
        	"startColour": [50, 200, 50, 1],
        	"startColourRandom": [10, 10, 10, 0.25],
        	"endColour": [50, 200, 50, 1],
        	"endColourRandom": [10, 10, 10, 0]
        },
        'fogCloud': {
        	"angle": 0,
        	"angleRandom": 360,
        	"duration": 100,
        	"emissionRate": 64,
        	"endColour": [100, 100, 100, 1],
        	"endColourRandom": [0, 0, 0, 0],
        	"gravity": {"x":0.01, "y":0.01},
        	"lifeSpan": 10,
        	"lifeSpanRandom": 0,
        	"maxParticles": 800,
        	"size": 70,
        	"sizeRandom": 10,
        	"speed": 25,
        	"speedRandom": 1.5,
        	"startColour": [50, 50, 50, 0.5],
        	"startColourRandom": [0, 0, 0, 0.25]
        },
        'synapticstatic': {
        	"angle": 0,
        	"angleRandom": 360,
        	"duration": 50,
        	"emissionRate": 100,
        	"endColour": [150, 100, 200, 1],
        	"endColourRandom": [0, 0, 0, 0],
        	"gravity": {"x":0.01, "y":0.01},
        	"lifeSpan": 10,
        	"lifeSpanRandom": 0,
        	"maxParticles": 500,
        	"size": 20,
        	"sizeRandom": 4,
        	"speed": 30,
        	"speedRandom": 1.5,
        	"startColour": [150, 100, 200, 1],
        	"startColourRandom": [0, 0, 0, 0.25]
        }
};


function gunshot(t1, t2, type) {
    if (type == null) type = 'revolver';
    let token1 = getToken(t1);
    let token2 = getToken(t2);
    if (token1 == null || token2 == null) return;
    calculateGunshot(token1.get('left'), token1.get('top'), token2.get('left'), token2.get('top'), type);
}

async function calculateGunshot(x1, y1, x2, y2, type) {
    if (type == null) type = 'revolver';
    playSound(type);
    let theta = await calculateAngle(x1,y1,x2,y2);
    theta = theta * 180 / Math.PI;
    if (theta < 0) theta += 360;
    let lifespan = await calculateDistance(x1,y1,x2,y2);
    lifespan /= 200;
    await sleepMS(500);
    let duration = lifespan;
    let max_particles = 1;
    let emission_rate = 1;
    if (type == 'gatling') {
        duration *= 20;
        emission_rate = 0.3;
        max_particles = 200;
    }
    spawnFxWithDefinition(x1, y1, {
        angle: theta,
        angleRandom: 0.1,        
    	duration: duration,
    	emissionRate: emission_rate,
    	endColour: [32, 32, 32, 0.5],
    	endColourRandom: [0, 0, 0, 0],
    	lifeSpan: lifespan,
    	lifeSpanRandom: 0,
    	maxParticles: max_particles,
        gravity: { x: 0.01, y: 0.01 },
    	size: 30,
    	sizeRandom: 0,
    	speed: 200,
    	speedRandom: 0,
    	startColour: [32, 32, 32, 1],
    	startColourRandom: [0, 0, 0, 0]
    });
    //debugging('angle: ' + theta);
}
