//For spells where the number of targets scale with spell level, we have created a special syntax to interpret the number of targets from the spell level.
//it looks kinda like this:
//"paramName[expr]=\'&#64;{target|Param Name $|token_name}\'"
//
//for 'expr', you want to use the word 'level' to represent the level, then some simple math statement. 
//for example, 'bless' lets you bless a number of allies equal to the spell level plus 2.
//I want my param to be called 'ally', so I use: "ally[level+2]=\'&#64;{target|Ally $|token_name}\'"
//
//the calculateHref method will resolve "[level+2]" based on the level you are invoking the spell, then iteratively add
//ally1=..., ally2=..., ally3=..., and then replace the $ with 1,2,3

var spellTemplates = {
    "AbsorbElements": "caster='&#64;{target|Caster|token_name}'",
    "AcidSplash": "dmg=?{How much damage did you roll?}",
    "Aid":  "ally1='&#64;{target|Ally 1|token_name}' ally2='&#64;{target|Ally 2|token_name}' ally3='&#64;{target|Ally 3|token_name}'",
    "AnimateObjects": "tiny=?{How many tiny objects?} small=?{How many small objects?} medium=?{How many medium objects?} large=?{How many large objects?} huge=?{How many huge objects?}",
    "Antagonize": "target='&#64;{target|Target|token_name}' dmg=?{How much damage did you roll?}",
    "ArmorOfAgathys": "",
    "AuraOfVitality": "",
    "Bane": "target[level+2]='&#64;{target|Target $|token_name}'",
    "Banishment": "target[level-3]='&#64;{target|Target $|token_name}'",
    "BeaconOfHope": "",
    "BestowCurse": "target='&#64;{target|Target|token_name}'",
    "Bless": "ally[level+2]='&#64;{target|Ally $|token_name}'",
    "BlindingSmite": "target='&#64;{target|Target|token_name}' dmgType2=?{What type of damage does your normal weapon deal?|Bludgeoning|Piercing|Slashing} dmg2=?{How much damage did your base weapon do?} dmg=?{How much radiant damage did you roll?}",
    "BlindnessDeafness": "mode=?{Which mode are you using|Blindness|Deafness} target[level-1]='&#64;{target|Target $|token_name}'",
    "BloodBolt": "target='&#64;{target|Target|token_name}' dmg1=?{How much piercing damage did you roll?} dmg2=?{How much necrotic damage did you roll?}",
    "Blur": "",
    "BoomingBlade": "target='&#64;{target|Target|token_name}'  dmgType2=?{What kind of damage does your weapon deal?|Bludgeoning|Piercing|Slashing} dmg2=?{How much damage did the base weapon do?} dmg=?{How much thunder damage did you roll?}",
    "BurningHands": "dmg=?{How much damage did you roll?}",
    "CalmEmotions": "",
    "Catapult": "dmg=?{How much damage did you roll?}",
    "ChaosBolt": "target='&#64;{target|Target|token_name}' type=?{What damage type did you roll?|Roll|Acid|Cold|Fire|Force|Lightning|Poison|Psychic|Thunder} dmg=?{How much damage did you roll?}",
    "CharmPerson": "target[level]='&#64;{target|Target $|token_name}'",
    "ChillTouch": "target='&#64;{target|Target|token_name}' dmg=?{How much damage did you roll?}",
    "ChromaticOrb": "target='&#64;{target|Target|token_name}' type=?{What damage type are you using?|Acid|Cold|Fire|Lightning|Poison|Thunder} dmg=?{How much damage did you roll?}",
    "CircleOfPower": "",
    "CloudOfDaggers": "",
    "ColorSpray": "dmg=?{How many hit points did you roll?}",
    "Command": "target[level]='&#64;{target|Target $|token_name}' command=?{What command did you give?}",
    "CompelledDuel": "target='&#64;{target|Target|token_name}'",
    "Counterspell": "caster='&#64;{target|Who is casting counterspell?|token_name}' target='&#64;{target|Who is being counterspelled?|token_name}'",
    "CreateWater": "",
    "CrownOfMadness": "target='&#64;{target|Target|token_name}'",
    "CureWounds": "target='&#64;{target|Target|token_name}' healing=?{How much HP did you restore?}",
    "DetectEvilAndGood": "",
    "DetectMagic": "",
    "DetectPoisonAndDisease": "",
    "DissonantWhispers": "target='&#64;{target|Target|token_name}' dmg=?{How much damage did you roll?}",
    "DivineFavor": "",
    "DivineSmite": "target='&#64;{target|Target|token_name}' dmgType2=?{What type of damage does your normal weapon deal?|Bludgeoning|Piercing|Slashing} dmg2=?{How much damage did your base weapon do?} dmg=?{How much radiant damage did you roll?}",
    "EldritchBlast": "target[level]='&#64;{target|Target $|token_name}' dmg[level]=?{How much damage did you roll on blast $? (Leave blank if you missed)}",
    "EnhanceAbility": "stat=?{Select ability|Strength|Dexterity|Constitution|Intelligence|Wisdom|Charisma} target[level-1]='&#64;{target|Target $|token_name}'",
    "EnlargeReduce": "target='&#64;{target|Target|token_name}' mode=?{Which mode are you using?|Enlarge|Reduce}",
    "EnsnaringStrike": "target='&#64;{target|token_name}' dmg=?{How much damage did you roll on your weapon attack? (Put 0 if you already manually updated the HP)}",
    "ExpeditiousRetreat": "",
    "Exsanguinate": "target='&#64;{target|Target|token_name}' dmg=?{How much damage did you roll on the first set of dice?} dmgExtra=?{How much damage did you roll on the second set of dice (assuming target is bloodied)?}",
    "FaerieFire": "",
    "FalseLife": "tempHP=?{How much temp HP do you gain?}",
    "Fear": "",
    "FeatherFall": "ally1='&#64;{target|Ally 1|token_name}' ally2='&#64;{target|Ally 2|token_name}' ally3='&#64;{target|Ally 3|token_name}' ally4='&#64;{target|Ally 4|token_name}' ally5='&#64;{target|Ally 5|token_name}'",
    "Fireball": "dmg=?{How much damage did you roll?}",
    "Firebolt": "target='&#64;{target|Target|token_name}' dmg=?{How much damage did you roll?}",
    "FlamingSphere": "",
    "FogCloud": "",
    "FreedomOfMovement": "target='&#64;{target|Target|token_name}'",
    "Frostbite": "target='&#64;{target|Target|token_name}' dmg=?{How much damage did you roll?}",
    "GabrielsChromaticBurst": "target='&#64;{target|Target|token_name}' type=?{What damage type are you using?|Acid|Cold|Fire|Lightning|Poison|Thunder} dmg=?{How much damage did the regular attack do (Put 0 or leave blank if you missed)?} dmg2=?{How much damage did the explosion do?}",
    "Goodberry": "target='&#64;{target|Target|token_name}'",
    "Grease": "",
    "GravityWell": "target='&#64;{target|Target|token_name}' dmg=?{How much damage did you roll?}",
    "GreenFlameBlade": "target='&#64;{target|Who takes the primary attack?|token_name}' target2='&#64;{target|Who does the flame leap to?|token_name}' dmgType2=?{What kind of damage does your weapon deal?|Bludgeoning|Piercing|Slashing} dmg2=?{How much damage did the base weapon do?} dmg3=?{How much fire damage did you do to the primary target?} dmg=?{How much fire damage did you to the person the flame leapt to?}",
    "Guidance": "ally='&#64;{target|Ally|token_name}'",
    "GuidingBolt": "target='&#64;{target|Target|token_name}' dmg=?{How much damage did you roll?}",
    "GustOfWind": "",
    "HailOfThorns": "target='&#64;{target|Target|token_name}' dmg=?{How much damage did your normal weapon attack do (Put 0 or leave blank if you missed)?} dmg2=?{How much damage did your spell do?}",
    "Haste": "ally='&#64;{target|Ally|token_name}'",
    "HealingWord": "target='&#64;{target|Target|token_name}' healing=?{How much HP did you restore?}",
    "HeatMetal": "target='&#64;{target|Target|token_name}' dmg=?{How much damage did you roll?}",
    "HellishRebuke": "caster='&#64;{target|Caster|token_name}' target='&#64;{target|Target|token_name}' dmg=?{How much damage did you roll?}",
    "HemorrhagingCurse": "target='&#64;{target|Target|token_name}'",
    "Heroism": "ally[level]='&#64;{target|Ally $|token_name}'",
    "Hex": "target='&#64;{target|Target|token_name}' stat=?{Which stat are you hexing?|STR|DEX|CON|INT|WIS|CHA}",
    "HoldMonster": "target[level-4]='&#64;{target|Target $|token_name}'",
    "HoldPerson": "target[level-1]='&#64;{target|Target $|token_name}'",
    "HuntersMark": "target='&#64;{target|Target|token_name}'",
    "HypnoticPattern": "",
    "IceKnife": "target='&#64;{target|Target|token_name}' dmg=?{How much piercing damage did the attack do (Put 0 or leave blank if you missed)?} dmg2=?{How much damage did the explosion do?}",
    "IceStorm": "dmg=?{How much bludgeoning damage did the spell do?} dmg2=?{How much cold damage did the spell do?}",
    "IllusionaryDart": "target[level]='&#64;{target|Target $|token_name}' dmg[level]=?{How much damage did you roll on dart $? (Leave blank if you missed)}",
    "InflictWounds": "target='&#64;{target|Target|token_name}' dmg=?{How much damage did you roll?}",
    "IntellectFortress": "ally[level-2]='&#64;{target|Ally $|token_name}'",
    "Invisibility": "target[level-1]='&#64;{target|Target $|token_name}'",
    "Jump": "target='&#64;{target|Target|token_name}'",
    "LesserRestoration": "ally='&#64;{target|Ally|token_name}' condition=?{What condition are you removing?|Blinded|Deafened|Paralyzed|Poisoned}",
    "Levitate": "target='&#64;{target|Target|token_name}'",
    "Light": "target='&#64;{target|Target|token_name}'",
    "LightningBolt": "dmg=?{How much damage did this spell deal?}",
    "MageArmor": "",
    "MageHand": "",
    "MagicMissile": "target[level+2]='&#64;{target|Target $|token_name}' dmg[level+2]=?{How much damage did you roll on missile $?}",
    "MassCureWounds": "target1='&#64;{target|Target 1|token_name}' target2='&#64;{target|Target 2|token_name}' target3='&#64;{target|Target 3|token_name}' target4='&#64;{target|Target 4|token_name}' target5='&#64;{target|Target 5|token_name}' target6='&#64;{target|Target 6|token_name}' healing=?{How much HP did you restore to each ally?}",
    "MassHealingWord": "target1='&#64;{target|Target 1|token_name}' target2='&#64;{target|Target 2|token_name}' target3='&#64;{target|Target 3|token_name}' target4='&#64;{target|Target 4|token_name}' target5='&#64;{target|Target 5|token_name}' target6='&#64;{target|Target 6|token_name}' healing=?{How much HP did you restore to each ally?}",
    "MaximilliansEarthenGrasp": "target='&#64;{target|Target|token_name}' dmg=?{How much damage did you roll?}",
    "MelfsAcidArrow": "target='&#64;{target|Target|token_name}' dmg=?{How much acid damage was dealt?} hit=?{Did the attack hit the target?|Yes|No}",
    "MindSliver": "target='&#64;{target|Target|token_name}' dmg=?{How much damage did you roll?}",
    "MirrorImage": "",
    "Moonbeam": "",
    "OtilukesResilientSphere": "target='&#64;{target|Target|token_name}'",
    "PassWithoutTrace": "",
    "Polymorph": "target1='&#64;{target|Target|token_name}' tempHP=?{How much HP does its new form have?}",
    "ProduceFlame": "target='&#64;{target|Target|token_name}' dmg=?{How much damage did you roll?}",
    "ProtectionFromEnergy": "ally='&#64;{target|Ally|token_name}' type=?{What energy type are you providing protection against?|Acid|Cold|Fire|Lightning|Thunder}",
    "ProtectionFromEvilAndGood": "ally='&#64;{target|Target|token_name}'",
    "RayOfFrost": "target='&#64;{target|Target|token_name}' dmg=?{How much damage did you roll?}",
    "RayOfSickness": "target='&#64;{target|Target|token_name}' dmg=?{How much damage did you roll?}",
    "SacredFlame": "target='&#64;{target|Target|token_name}' dmg=?{How much damage did you roll?}",
    "Sanctuary": "target='&#64;{target|Target|token_name}'",
    "SanguineSpears": "mode=?{Are you attacking with existing spears or creating new ones?|Attacking|Creating} target='&#64;{target|Target (Click Any Token if Just Creating Spears)|token_name}' dmg1=?{How much piercing damage did you roll? (leave blank if just creating spears)} dmg2=?{How much necrotic damage did you roll? (leave blank if just creating spears)}",
    "SearingSmite": "target='&#64;{target|Target|token_name}' dmgType2=?{What type of damage does your normal weapon deal?|Bludgeoning|Piercing|Slashing} dmg2=?{How much damage did your base weapon do?} dmg=?{How much fire damage did you roll?}",
    "Shatter": "dmg=?{How much damage did you roll?}",
    "Shield": "caster='&#64;{target|Caster|token_name}'",
    "ShieldOfFaith": "ally='&#64;{target|Ally|token_name}'",
    "ShockingGrasp": "target='&#64;{target|Target|token_name}' dmg=?{How much damage did you roll?}",
    "SickeningRadiance": "",
    "Silence": "",
    "SilveryBarbs": "target='&#64;{target|Target|token_name}' ally='&#64;{target|Ally|token_name}'",
    "Sleep": "dmg=?{How many hit points did you roll?}",
    "Slow": "",
    "SpiritGuardians": "dmgType=?{What type of damage?|Radiant|Necrotic}",
    "SpiritualWeapon": "",
    "StarryWisp": "target='&#64;{target|Target|token_name}' dmg=?{How much damage did you roll?}",
    "SummonBeast": "type=?{Which environment|Land|Air|Water}",
    "SummonConstruct": "type=?{Which type of material?|Clay|Metal|Stone}",
    "SynapticStatic": "dmg=?{How much damage did you roll?}",
    "TashasCausticBrew": "",
    "TashasHideousLaughter": "target='&#64;{target|Target|token_name}'",
    "Thaumaturgy": "",
    "Thunderclap": "dmg=?{How much damage did you roll?}",
    "Thunderwave": "dmg=?{How much damage did you roll?}",
    "TollTheDead": "target='&#64;{target|Target|token_name}' dmg=?{How much damage did you roll?}",
    "ViciousMockery": "target='&#64;{target|Target|token_name}' dmg=?{How much damage did you roll?}",
    "WardingBond": "ally='&#64;{target|Ally|token_name}'",
    "Web": "",
    "WebOfFire": "target1='&#64;{target|Target 1|token_name}' target2='&#64;{target|Target 2 (Click any token if single-target)|token_name}' target3='&#64;{target|Target 3 (Click any token if single-target)|token_name}' target4='&#64;{target|Target 4 (Click any token if single-target)|token_name}' target5='&#64;{target|Target 5 (Click any token if single-target)|token_name}' dmg1=?{How much damage to the first target?} dmg2=?{How much damage to the second target? (Leave blank if only a single target was selected)} dmg3=?{How much damage to the third target? (Leave blank if only a single target was selected)} dmg4=?{How much damage to the fourth target? (Leave blank if only a single target was selected)} dmg5=?{How much damage to the fifth target? (Leave blank if only a single target was selected)}",
    "WitherAndBloom": "dmg=?{How much damage did you roll?}",
    "WordOfRadiance": "dmg=?{How much damage did you roll?}",
    "WrathfulSmite": "target='&#64;{target|Target|token_name}' dmgType2=?{What type of damage does your normal weapon deal?|Bludgeoning|Piercing|Slashing} dmg2=?{How much damage did your base weapon do?} dmg=?{How much psychic damage did you roll?}",
}
